spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/haru-speak?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    password: haru-speak-1234

logging:
  level:
    org.hibernate.SQL: debug
    com.example:
      be: debug
